FROM node:12

# Create app directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

ENV PATH /usr/src/node_modules/.bin:$PATH

# Bundle app source
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . ./

EXPOSE 4000

# Allows override to shell directly
CMD [ "npm" , "run" , "dev" ]
